### ISSUE TITLE
Price format

### ISSUE THREAD

**Issue by kiddkid99** [chiayi50446/ASP_NET_MVC_Q2#1]
Price 及 PromotePrice 需要依照 Locale 轉換成對應的貨幣格式

EX: if Locale = "US" , Price = "$10.00"

**Comment by chiayi50446** [comment]
OK, Got it
已修正

**Comment by kiddkid99** [comment]
還需要考慮到千分位，小數點的格式，可以使用 .NET 的格式化貨幣字串，使用符合的文化特性做轉換

**Comment by chiayi50446** [comment]
OK, Got
已修正
