### ISSUE TITLE
Use ViewModel

### ISSUE THREAD

**Issue by kiddkid99** [chiayi50446/ASP_NET_MVC_Q2#2]
使用 ViewModel 的目的

1. 避免在 View 呈現使用太多邏輯判斷，View 去呈現 Model 的內容，過程應該越簡單越好
2. 如果使用 ViewModel ，與資料存取 Model 的轉換過程，建議自己處理

**Comment by chiayi50446** [comment]
已修正，但不確定是否符合viewModel的使用要求

**Comment by kiddkid99** [comment]
盡量不要再不同 View 使用同一個 ViewModel
因為這題例子太單純還看不出來，複雜情況這樣的 ViewModel 會變得很難維護
例如在一個 View 出現太多用不到的屬性，造成混淆

**Comment by chiayi50446** [comment]
OK,
已修正

**Comment by kiddkid99** [comment]
編譯出現錯誤
錯誤	CS0246	找不到類型或命名空間名稱 'ProductDetailViewModel' (是否遺漏了 using 指示詞或組件參考?)

要把 ProductDetailViewModel 這個檔案 "加入至專案"

**Comment by chiayi50446** [comment]
OK, 
已將 ProductDetailViewModel 加入至專案
