### ISSUE TITLE
Repository 的職責

### ISSUE THREAD

**Issue by kiddkid99** [chiayi50446/ASP_NET_MVC_Q2#3]
Repository 的職責需要更加明確
此題的 Repository 設計只需要兩個 public method

1. GetList
2. GetById

至於貨幣轉換格式，讓表現層來處理比較好一點
目前屬於表現層的範圍為 View, Controller, ViewModel
可以思考這部分的處理應該寫在那會比較好

**Comment by chiayi50446** [comment]
OK,
已修正
我將貨幣轉換格式在detail view處理，因貨幣轉換僅與detail view有關
